name = "Nomifactory-CEu-packwiz"
author = "TM4"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3bad89cc4e4cbcd10ad68a3fceda9d49af438dc6cb52fc9293d4c4488cd8564"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
