name = "Nomifactory-CEu-packwiz"
author = "TM4"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eba91fc05c31bca88dcddf947c72c334b5c2b16e0d3f9d1e84e46635981679b8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
